M48
; DRILL file {KiCad 9.0.0} date 2025-11-26T22:34:38-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-26T22:34:38-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X19.185Y33.04
X19.185Y27.26
T2
X6.39Y25.581
X6.39Y23.549
X11.47Y24.565
M30
